"""Generic symmetry-basis draft for GNME state SDPs.

This module is a structural prototype for the *real* symmetry-adapted SDP
variables. It intentionally avoids hand-written case distinctions per symmetry
type at the variable-construction level.

The guiding idea is:

1. keep the combinatorics from ``GNMEProblem``,
2. read the local symmetry action from ``local_symmetry_perms``,
3. build the real symmetric invariant basis generated by that action,
4. count one scalar parameter per basis element.

For permutation symmetries acting on tensor slots, the invariant basis of real
symmetric matrices is exactly the orbit basis of upper-triangular matrix
entries. This is the same generic real formulation already used in the current
solver backend, but exposed here as a dedicated structural draft.
"""

from __future__ import annotations

from dataclasses import dataclass
from time import perf_counter
from typing import Dict, Iterable, List, Tuple

from ..GNMEProblem import GNMEProblem
from .GNMEStateSDP import (
    _basis_permutation_map,
    _progress_log,
    _resolve_verbose,
    product_dim,
    symmetric_matrix_orbits,
)


@dataclass(frozen=True)
class BlockSectorDraft:
    """One symmetry-adapted PSD block in the draft decomposition."""

    label: str
    field: str
    irrep_dim: int
    multiplicity: int
    projector_rank: int
    scalar_parameter_count: int


@dataclass(frozen=True)
class BlockVariableDraft:
    """Generic symmetry-basis structure of one full GNME inflation variable."""

    name: str
    lexorder: Tuple[str, ...]
    slot_dims: Tuple[int, ...]
    matrix_dim: int
    symmetry_group_size: int
    symmetry_type: str
    upper_triangular_entries: int
    orbit_parameter_count: int
    block_parameter_count: int
    sectors: Tuple[BlockSectorDraft, ...]
    factorization: Tuple[Tuple[str, ...], ...]


@dataclass(frozen=True)
class GNMEBlockSDPDraft:
    """Draft description of the block-reduced full SDP variables."""

    n_parties: int
    inflation_level: int
    party_dims: Dict[str, int]
    variables: Tuple[BlockVariableDraft, ...]


def _upper_triangular_parameter_count(size: int) -> int:
    """Number of real parameters in a symmetric matrix of given size."""
    return size * (size + 1) // 2


def _hermitian_parameter_count(size: int) -> int:
    """Number of real parameters in a complex Hermitian matrix."""
    return size * size


def _permutation_parity(permutation: Tuple[int, ...]) -> int:
    """Sign of a permutation written in one-line notation."""
    visited = [False] * len(permutation)
    parity = 1
    for start in range(len(permutation)):
        if visited[start]:
            continue
        cursor = start
        cycle_length = 0
        while not visited[cursor]:
            visited[cursor] = True
            cursor = permutation[cursor]
            cycle_length += 1
        if cycle_length > 0 and cycle_length % 2 == 0:
            parity *= -1
    return parity


def _basis_permutation_trace(basis_map: Tuple[int, ...]) -> int:
    """Trace of the permutation matrix induced by a basis relabeling."""
    return sum(1 for index, image in enumerate(basis_map) if index == image)


def _classify_local_symmetry(
    slot_permutations: Tuple[Tuple[int, ...], ...],
) -> str:
    """Classify the currently supported local symmetry groups."""
    group_size = len(slot_permutations)
    if group_size == 1:
        return "trivial"
    if group_size == 2:
        return "Z2"
    if group_size == 3:
        return "C3"
    if group_size == 6:
        return "S3"
    return "unsupported"


def _basis_representation_matrices(
    slot_dims: Tuple[int, ...],
    local_symmetry_perms: Tuple[Tuple[int, ...], ...],
) -> Tuple[Tuple[int, ...], ...]:
    """Unique basis-index permutations induced by the local symmetry group."""
    seen = set()
    basis_maps = []
    for permutation in local_symmetry_perms:
        basis_map = _basis_permutation_map(slot_dims, permutation)
        if basis_map not in seen:
            seen.add(basis_map)
            basis_maps.append(basis_map)
    return tuple(basis_maps)


def _z2_block_sectors(basis_maps: Tuple[Tuple[int, ...], ...]) -> Tuple[BlockSectorDraft, ...]:
    """Legacy helper retained for reference."""
    if len(basis_maps) != 2:
        raise ValueError("Z2 block draft expects exactly two group elements.")
    dim = len(basis_maps[0])
    generator_trace = next(
        _basis_permutation_trace(basis_map)
        for basis_map in basis_maps
        if any(index != image for index, image in enumerate(basis_map))
    )
    multiplicity_plus = (dim + generator_trace) // 2
    multiplicity_minus = (dim - generator_trace) // 2
    return (
        BlockSectorDraft(
            label="symmetric",
            field="real",
            irrep_dim=1,
            multiplicity=multiplicity_plus,
            projector_rank=multiplicity_plus,
            scalar_parameter_count=_upper_triangular_parameter_count(multiplicity_plus),
        ),
        BlockSectorDraft(
            label="antisymmetric",
            field="real",
            irrep_dim=1,
            multiplicity=multiplicity_minus,
            projector_rank=multiplicity_minus,
            scalar_parameter_count=_upper_triangular_parameter_count(multiplicity_minus),
        ),
    )


def _c3_block_sectors(basis_maps: Tuple[Tuple[int, ...], ...]) -> Tuple[BlockSectorDraft, ...]:
    """Legacy helper retained for reference."""
    dim = len(basis_maps[0])
    traces = sorted(_basis_permutation_trace(basis_map) for basis_map in basis_maps)
    trivial_rank = sum(traces) // 3
    nontrivial_rank = dim - trivial_rank
    if nontrivial_rank % 2 != 0:
        raise ValueError("C3 non-trivial sector rank must be even.")
    multiplicity_rotation = nontrivial_rank // 2
    return (
        BlockSectorDraft(
            label="trivial",
            field="real",
            irrep_dim=1,
            multiplicity=trivial_rank,
            projector_rank=trivial_rank,
            scalar_parameter_count=_upper_triangular_parameter_count(trivial_rank),
        ),
        BlockSectorDraft(
            label="rotation",
            field="complex",
            irrep_dim=2,
            multiplicity=multiplicity_rotation,
            projector_rank=nontrivial_rank,
            scalar_parameter_count=_hermitian_parameter_count(multiplicity_rotation),
        ),
    )


def _s3_block_sectors(
    slot_permutations: Tuple[Tuple[int, ...], ...],
    basis_maps: Tuple[Tuple[int, ...], ...],
) -> Tuple[BlockSectorDraft, ...]:
    """Legacy helper retained for reference."""
    if len(slot_permutations) != 6 or len(basis_maps) != 6:
        raise ValueError("S3 block draft expects six group elements.")
    dim = len(basis_maps[0])
    traces = [_basis_permutation_trace(basis_map) for basis_map in basis_maps]
    rank_trivial = sum(traces) // 6
    signed_trace_sum = sum(
        _permutation_parity(permutation) * trace
        for permutation, trace in zip(slot_permutations, traces)
    )
    rank_sign = signed_trace_sum // 6
    rank_standard = dim - rank_trivial - rank_sign
    if rank_standard % 2 != 0:
        raise ValueError("The S3 standard sector rank must be even.")
    multiplicity_standard = rank_standard // 2
    return (
        BlockSectorDraft(
            label="trivial",
            field="real",
            irrep_dim=1,
            multiplicity=rank_trivial,
            projector_rank=rank_trivial,
            scalar_parameter_count=_upper_triangular_parameter_count(rank_trivial),
        ),
        BlockSectorDraft(
            label="sign",
            field="real",
            irrep_dim=1,
            multiplicity=rank_sign,
            projector_rank=rank_sign,
            scalar_parameter_count=_upper_triangular_parameter_count(rank_sign),
        ),
        BlockSectorDraft(
            label="standard",
            field="real",
            irrep_dim=2,
            multiplicity=multiplicity_standard,
            projector_rank=rank_standard,
            scalar_parameter_count=_upper_triangular_parameter_count(multiplicity_standard),
        ),
    )


def _generic_invariant_basis_sector(
    lexorder: Tuple[str, ...],
    slot_dims: Tuple[int, ...],
    local_symmetry_perms: Tuple[Tuple[int, ...], ...],
) -> Tuple[str, Tuple[BlockSectorDraft, ...], int]:
    """Determine the generic real symmetric invariant basis for one tau."""
    symmetry_type = _classify_local_symmetry(local_symmetry_perms)
    orbit_data = symmetric_matrix_orbits(slot_dims, local_symmetry_perms)
    sectors = (
        BlockSectorDraft(
            label="invariant_real_symmetric_basis",
            field="real",
            irrep_dim=1,
            multiplicity=len(orbit_data.orbit_representatives),
            projector_rank=orbit_data.matrix_dim,
            scalar_parameter_count=len(orbit_data.orbit_representatives),
        ),
    )
    return symmetry_type, sectors, len(orbit_data.orbit_representatives)


def build_block_sdp_draft(
    problem: GNMEProblem,
    subset_sizes: Tuple[int, ...] = (2, 3, 4),
    verbose: int | None = None,
) -> GNMEBlockSDPDraft:
    """Build the symmetry-block draft for the maximal GNME inflations."""
    real_verbose = _resolve_verbose(verbose, getattr(problem, "verbose", 0))
    total_start = perf_counter()
    _progress_log(real_verbose, 1, "Building GNME block-SDP draft...")
    blueprint = problem.sdp_blueprint(
        subset_sizes=subset_sizes,
        include_known_marginals=True,
        min_shared_occurrences=2,
        min_shared_inflations=2,
    )
    _progress_log(
        real_verbose,
        1,
        "Block draft blueprint ready: "
        f"{len(blueprint.variables)} full inflations, "
        f"{len(blueprint.shared_subset_classes)} shared subset classes.",
    )

    block_variables: List[BlockVariableDraft] = []
    for index, variable in enumerate(blueprint.variables, start=1):
        step_start = perf_counter()
        _progress_log(
            real_verbose,
            1,
            f"  block variable {index}/{len(blueprint.variables)}: {variable.name}",
        )
        symmetry_type, sectors, basis_size = _generic_invariant_basis_sector(
            variable.lexorder,
            variable.slot_dims,
            variable.local_symmetry_perms,
        )
        matrix_dim = product_dim(variable.slot_dims)
        upper_entries = matrix_dim * (matrix_dim + 1) // 2
        orbit_parameter_count = basis_size
        block_parameter_count = basis_size
        block_variables.append(
            BlockVariableDraft(
                name=variable.name,
                lexorder=variable.lexorder,
                slot_dims=variable.slot_dims,
                matrix_dim=matrix_dim,
                symmetry_group_size=len(variable.local_symmetry_perms),
                symmetry_type=symmetry_type,
                upper_triangular_entries=upper_entries,
                orbit_parameter_count=orbit_parameter_count,
                block_parameter_count=block_parameter_count,
                sectors=sectors,
                factorization=variable.factorization,
            )
        )
        _progress_log(
            real_verbose,
            1,
            f"    symmetry={symmetry_type}, "
            f"upper={upper_entries}, orbit-params={orbit_parameter_count}, "
            f"block-params={block_parameter_count} "
            f"in {perf_counter() - step_start:.2f}s.",
        )

    draft = GNMEBlockSDPDraft(
        n_parties=problem.n_parties,
        inflation_level=problem.inflation_level,
        party_dims=dict(blueprint.party_dims),
        variables=tuple(block_variables),
    )
    _progress_log(
        real_verbose,
        1,
        "GNME block-SDP draft ready in "
        f"{perf_counter() - total_start:.2f}s.",
    )
    return draft


def print_block_draft(draft: GNMEBlockSDPDraft) -> None:
    """Human-readable summary of the block draft."""
    print("GNME Block-SDP Draft")
    print(f"  parties: {draft.n_parties}")
    print(f"  inflation level: {draft.inflation_level}")
    print(f"  party dims: {draft.party_dims}")
    print()
    for variable in draft.variables:
        print(f"{variable.name}:")
        print(f"  lexorder: {' '.join(variable.lexorder)}")
        print(f"  symmetry type: {variable.symmetry_type}")
        print(f"  symmetry group size: {variable.symmetry_group_size}")
        print(f"  slot dims: {variable.slot_dims}")
        print(f"  matrix dim: {variable.matrix_dim}")
        print(f"  upper-triangular entries: {variable.upper_triangular_entries}")
        print(f"  orbit parameter count: {variable.orbit_parameter_count}")
        print(f"  block parameter count: {variable.block_parameter_count}")
        print("  sectors:")
        for sector in variable.sectors:
            print(
                "    "
                f"{sector.label}: field={sector.field}, irrep_dim={sector.irrep_dim}, "
                f"multiplicity={sector.multiplicity}, projector_rank={sector.projector_rank}, "
                f"parameters={sector.scalar_parameter_count}"
            )
        print(f"  factorization: {variable.factorization}")
        print()


__all__ = [
    "BlockSectorDraft",
    "BlockVariableDraft",
    "GNMEBlockSDPDraft",
    "build_block_sdp_draft",
    "print_block_draft",
]
